name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore CurrencyConverterAPI/CurrencyConverterAPI.csproj

      - name: Build
        run: dotnet build CurrencyConverterAPI/CurrencyConverterAPI.csproj --configuration Release --no-restore

      - name: Find all DLLs
        run: find . -name "*.dll"


      - name: Run tests
        run: dotnet test CurrencyConverterAPI.Tests/CurrencyConverterAPI.Tests.csproj --configuration Release --no-build --logger trx --results-directory TestResults --verbosity diagnostic

      
